import {Footer, Navbar} from "@/components/shared";
import ReduxProvider from "./ReduxProvider";
import "./main.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <main className="w-full max-w-screen h-full min-h-screen bg-[#F8F0EC] grid layout">
            <Navbar />
            <div
              className="w-full h-full max-w-screen"
              style={{gridArea: "main"}}
            >
              {children}
            </div>
            <Footer />
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
